structure(list(url = "https://xkcd.com/rss.xml", status_code = 200L, 
    headers = structure(list(connection = "keep-alive", `content-length` = "876", 
        server = "nginx", `content-type` = "text/xml", `last-modified` = "Mon, 24 Feb 2020 05:00:07 GMT", 
        etag = "W/\"5e535857-aad\"", expires = "Mon, 24 Feb 2020 05:06:02 GMT", 
        `cache-control` = "max-age=300", `content-encoding` = "gzip", 
        `accept-ranges` = "bytes", date = "Mon, 24 Feb 2020 16:00:20 GMT", 
        via = "1.1 varnish", age = "232", `x-served-by` = "cache-dal21240-DAL", 
        `x-cache` = "HIT", `x-cache-hits` = "1", `x-timer` = "S1582560020.445381,VS0,VE0", 
        vary = "Accept-Encoding"), class = c("insensitive", "list"
    )), all_headers = list(list(status = 301L, version = "HTTP/1.1", 
        headers = structure(list(server = "Varnish", `retry-after` = "0", 
            location = "https://xkcd.com/rss.xml", `content-length` = "0", 
            `accept-ranges` = "bytes", date = "Mon, 24 Feb 2020 16:00:19 GMT", 
            via = "1.1 varnish", `x-served-by` = "cache-bur17533-BUR", 
            `x-cache` = "HIT", `x-cache-hits` = "0", `x-timer` = "S1582560020.635017,VS0,VE0", 
            `proxy-connection` = "Keep-Alive", connection = "Keep-Alive", 
            age = "0"), class = c("insensitive", "list"))), list(
        status = 200L, version = "HTTP/1.1", headers = structure(list(), .Names = character(0), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(connection = "keep-alive", `content-length` = "876", 
            server = "nginx", `content-type` = "text/xml", `last-modified` = "Mon, 24 Feb 2020 05:00:07 GMT", 
            etag = "W/\"5e535857-aad\"", expires = "Mon, 24 Feb 2020 05:06:02 GMT", 
            `cache-control` = "max-age=300", `content-encoding` = "gzip", 
            `accept-ranges` = "bytes", date = "Mon, 24 Feb 2020 16:00:20 GMT", 
            via = "1.1 varnish", age = "232", `x-served-by` = "cache-dal21240-DAL", 
            `x-cache` = "HIT", `x-cache-hits` = "1", `x-timer` = "S1582560020.445381,VS0,VE0", 
            vary = "Accept-Encoding"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<rss version=\"2.0\"><channel><title>xkcd.com</title><link>https://xkcd.com/</link><description>xkcd.com: A webcomic of romance and math humor.</description><language>en</language><item><title>Grandpa Jason and Grandpa Chad</title><link>https://xkcd.com/2271/</link><description>&lt;img src=\"https://imgs.xkcd.com/comics/grandpa_jason_and_grandpa_chad.png\" title=\"The AARP puts the average age of a first-time grandparent close to 50, and the CDC has some data. But I don't have first-parent age distributions for specific names, or generational first-child age correlations, so the dotted line is just a guess. Still, let's be honest: No further research is really *needed.*\" alt=\"The AARP puts the average age of a first-time grandparent close to 50, and the CDC has some data. But I don't have first-parent age distributions for specific names, or generational first-child age correlations, so the dotted line is just a guess. Still, let's be honest: No further research is really *needed.*\" /&gt;</description><pubDate>Fri, 21 Feb 2020 05:00:00 -0000</pubDate><guid>https://xkcd.com/2271/</guid></item><item><title>Picking Bad Stocks</title><link>https://xkcd.com/2270/</link><description>&lt;img src=\"https://imgs.xkcd.com/comics/picking_bad_stocks.png\" title=\"On the news a few days later: &amp;quot;Buzz is building around the so-called 'camping Roomba' after a big investment. Preorders have spiked, and...&amp;quot;\" alt=\"On the news a few days later: &amp;quot;Buzz is building around the so-called 'camping Roomba' after a big investment. Preorders have spiked, and...&amp;quot;\" /&gt;</description><pubDate>Wed, 19 Feb 2020 05:00:00 -0000</pubDate><guid>https://xkcd.com/2270/</guid></item><item><title>Phylogenetic Tree</title><link>https://xkcd.com/2269/</link><description>&lt;img src=\"https://imgs.xkcd.com/comics/phylogenetic_tree.png\" title=\"And I was kicked out of my March Madness pool because I wouldn't shut up about the evidence for NBA/ABA endosymbiosis.\" alt=\"And I was kicked out of my March Madness pool because I wouldn't shut up about the evidence for NBA/ABA endosymbiosis.\" /&gt;</description><pubDate>Mon, 17 Feb 2020 05:00:00 -0000</pubDate><guid>https://xkcd.com/2269/</guid></item><item><title>Further Research is Needed</title><link>https://xkcd.com/2268/</link><description>&lt;img src=\"https://imgs.xkcd.com/comics/further_research_is_needed.png\" title=\"Further research is needed to fully understand how we managed to do such a good job.\" alt=\"Further research is needed to fully understand how we managed to do such a good job.\" /&gt;</description><pubDate>Fri, 14 Feb 2020 05:00:00 -0000</pubDate><guid>https://xkcd.com/2268/</guid></item></channel></rss>"), 
    date = structure(1582560020, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.199121, namelookup = 6.6e-05, 
    connect = 0.124134, pretransfer = 0.648121, starttransfer = 0.820011, 
    total = 1.019194)), class = "response")
